export const PRODUCT_FORM_DEFAULTS = {
  name: '',
  description: '',
  howToUse: '',
  ingredients: '',
  sku: '',
  categoryId: '',
  categoryIds: [] as number[],
  vendorId: '1',
  brandId: '',
  images: [] as any[],
  tagsCsv: '',
  price: '',
  quantity: '',
  flashSale: false,
  flashSaleEndDate: '',
  discountId: '',
  promotionId: '',
};
