import "../globals.css";
import { Nunito } from "next/font/google";
import "../public/css/animate.min.css";
import "../public/css/animation.css";
import "../public/css/bootstrap-select.min.css";
import "../public/css/bootstrap.css";
import "../public/css/swiper-bundle.min.css";
import "../public/css/style.css";
import "../public/font/fonts.css";
import "../public/icon/style.css";
import { SessionProvider } from "next-auth/react";
import ToastProvider from "@/context/ToastProvider";
import { Toast } from "@radix-ui/react-toast";
 
const nunito = Nunito({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--nunito-font-family",
  display: "swap",
});
export const metadata = {
  title: "Remos eCommerce Admin Dashboard Next.js Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${nunito.variable} body`}>
        <ToastProvider />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
